name: build-fedora-bootc-custom
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * TUE'
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:
env:
    IMAGE_NAME: fedora-bootc-custom
    IMAGE_TAGS: latest 43
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  build-ghcr:
    name: Build images
    runs-on: ubuntu-24.04${{ matrix.arch }}
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        arch: ["", "-arm"]
        platform: ["linux"]
      fail-fast: false
    outputs:
      imageVersion: ${{ env.SHA_SHORT }}
    steps: 
      # Checkout push-to-registry action GitHub repository
      - name: Checkout Push to Registry action
        uses: actions/checkout@v4
          
      # Build metadata
      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ env.IMAGE_NAME }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/bcrochet/fedora-bootc-custom/main/README.md

      - name: Set short SHA
        run: |
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> "${GITHUB_ENV}"

      - name: Normalize arch to full name
        id: normalize
        run: |
          if [ "${{ env.ARCH }}" == "-arm" ]; then
            echo "ARCH=arm64" >> "${GITHUB_ENV}"
          elif [ "${{ env.ARCH }}" == "" ]; then
            echo "ARCH=amd64" >> "${GITHUB_ENV}"
          fi
        env:
          ARCH: ${{ matrix.arch }}

      # Build image using Buildah action
      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./Containerfile
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.SHA_SHORT }}-${{ matrix.platform }}-${{ env.ARCH }}
          archs: ${{ env.ARCH }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      # Push the image to GHCR (Image Registry)
      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ steps.registry_case.outputs.lowercase }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"

  push-ghcr:
    name: Push image
    needs: build-ghcr
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: true
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and add to manifest
        run: |
          buildah manifest create "${INPUT_NAME}"
          buildah manifest add "${INPUT_NAME}" "${IMAGE_REGISTRY}/${INPUT_NAME}:${INPUT_TAG}-linux-amd64"
          buildah manifest add "${INPUT_NAME}" "${IMAGE_REGISTRY}/${INPUT_NAME}:${INPUT_TAG}-linux-arm64"
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INPUT_NAME: ${{ env.IMAGE_NAME }}
          INPUT_TAG: ${{ needs.build-ghcr.outputs.imageVersion }}

      - name: Push manifest
        id: push-manifest
        run: |
            for version in ${INPUT_TAGS}; do
              podman manifest push --digestfile imagedigest "${INPUT_NAME}" "${IMAGE_REGISTRY}/${INPUT_NAME}:${version}" --all
            done
            echo "digest=$(cat imagedigest)" | tee -a "${GITHUB_OUTPUT}"
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INPUT_NAME: ${{ env.IMAGE_NAME }}
          INPUT_TAGS: ${{ needs.build-ghcr.outputs.imageVersion }} ${{ env.IMAGE_TAGS }}

      # Sign container
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.10.0
        with:
          cosign-release: 'v2.2.4'

      - name: Sign the published manifest
        if: github.event_name != 'pull_request'
        run: |
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY --recursive "${IMAGE_REGISTRY}/${INPUT_NAME}@${DIGEST}"
        env:
          DIGEST: ${{ steps.push-manifest.outputs.digest }}
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INPUT_NAME: ${{ env.IMAGE_NAME }}
          COSIGN_EXPERIMENTAL: false
          COSIGN_PRIVATE_KEY: ${{ secrets.SIGNING_SECRET }}

      - name: Verify the image signature
        run: |
          cosign verify \
            --key "https://github.com/${{ github.repository }}/cosign.pub@refs/heads/main" \
            "${IMAGE_REGISTRY}/${INPUT_NAME}@${DIGEST}"
        env:
          INPUT_NAME: ${{ env.IMAGE_NAME }}
          DIGEST: ${{ steps.push-manifest.outputs.digest }}
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}

